sudo: required

os:
  - osx

dist: trusty

language: rust
rust:
  - nightly-2016-09-21


env:
  - DEP_OPENSSL_INCLUDE=/usr/local/Cellar/openssl/1.0.2f/include/ OPENSSL_LIB_DIR=/usr/local/opt/openssl/lib

before_install:
  - brew install openssl

script:
  - cargo build
  - cargo test
